# Generated by Django 4.2.30 on 2026-06-24 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('group_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('max_members', models.PositiveIntegerField(default=512)),
                ('posting_restricted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_table',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='member', max_length=10)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groupapp.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_members',
                'indexes': [models.Index(fields=['user'], name='group_membe_user_id_88c209_idx'), models.Index(fields=['group', 'role'], name='group_membe_group_i_319a8c_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_change_group_info', models.BooleanField(default=False)),
                ('can_delete_messages', models.BooleanField(default=False)),
                ('can_add_admins', models.BooleanField(default=True)),
                ('can_delete_admins', models.BooleanField(default=False)),
                ('can_delete_group', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_group_permissions', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to='groupapp.group')),
            ],
            options={
                'db_table': 'group_admin_permissions',
                'unique_together': {('group', 'admin_user')},
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='groups_tabl_name_9b8375_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_type'], name='groups_tabl_group_t_43b5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_by'], name='groups_tabl_created_4b063a_idx'),
        ),
    ]
