# Generated by Django 4.2.30 on 2026-06-24 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_preview', models.CharField(blank=True, default='', help_text='Cached last message snippet for dashboard list — updated on every new message', max_length=200)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the last message — used for ordering', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('voice', 'Voice Note'), ('file', 'File'), ('pdf', 'PDF'), ('document', 'Document'), ('system', 'System')], default='text', max_length=20)),
                ('content_encrypted', models.TextField(blank=True, help_text='Client-side encrypted message content (ciphertext only)')),
                ('system_text', models.CharField(blank=True, help_text='Used only for system messages (type=system) — plaintext is safe here', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_for_everyone', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messageapp.conversation')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groupapp.group')),
                ('reply_to', models.ForeignKey(blank=True, help_text='The message this is a reply to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messageapp.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='messageapp.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_status',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messageapp.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_reactions',
            },
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_url', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('pdf', 'PDF'), ('document', 'Document')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration for audio/video files in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='messageapp.message')),
            ],
            options={
                'db_table': 'message_files',
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_muted', models.BooleanField(default=False)),
                ('muted_until', models.DateTimeField(blank=True, help_text='NULL means muted forever; a timestamp means muted until that time', null=True)),
                ('last_read_message_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messageapp.conversation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation_participants',
            },
        ),
        migrations.CreateModel(
            name='ArchivedConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_by', to='messageapp.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archived_conversations',
            },
        ),
        migrations.CreateModel(
            name='PinnedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='messageapp.conversation')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='groupapp.group')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='messageapp.message')),
                ('pinned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pinned_messages',
                'indexes': [models.Index(fields=['conversation'], name='pinned_mess_convers_aa78b7_idx'), models.Index(fields=['group'], name='pinned_mess_group_i_01eb74_idx')],
            },
        ),
        migrations.CreateModel(
            name='PinnedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('conversation', 'Conversation'), ('group', 'Group'), ('channel', 'Channel')], max_length=20)),
                ('item_id', models.BigIntegerField()),
                ('position', models.PositiveSmallIntegerField(help_text='Pin position 1–5 on the dashboard')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pinned_items',
                'indexes': [models.Index(fields=['user', 'position'], name='pinned_item_user_id_969d43_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pinneditem',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 1), ('position__lte', 5)), name='pin_position_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='pinneditem',
            constraint=models.UniqueConstraint(fields=('user', 'position'), name='uq_pin_position_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='pinneditem',
            unique_together={('user', 'item_type', 'item_id')},
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message'], name='message_sta_message_5f9800_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['recipient', 'is_read'], name='message_sta_recipie_242596_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagestatus',
            unique_together={('message', 'recipient')},
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='messagefile',
            index=models.Index(fields=['message'], name='message_fil_message_872ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='messages_convers_e551d4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['group', 'sent_at'], name='messages_group_i_18591d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='messages_sender__6ae55a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_pinned'], name='messages_is_pinn_d0688d_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('conversation__isnull', True), ('group__isnull', False)), models.Q(('conversation__isnull', False), ('group__isnull', True)), _connector='OR'), name='message_belongs_to_one_context'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user'], name='conversatio_user_id_4a2524_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation'], name='conversatio_convers_d44fde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='conversatio_updated_c163ba_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_by'], name='conversatio_created_bc3dde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='archivedconversation',
            unique_together={('user', 'conversation')},
        ),
    ]
