# Generated by Django 4.2.30 on 2026-06-24 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('banner', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('trading', 'Trading'), ('business', 'Business'), ('travel', 'Travel'), ('sports', 'Sports'), ('music', 'Music'), ('tech', 'Tech'), ('food', 'Food'), ('other', 'Other')], default='other', max_length=20)),
                ('channel_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10)),
                ('discoverable_consented_at', models.DateTimeField(blank=True, null=True)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('external_links', models.JSONField(blank=True, default=list, help_text="[{'label':'Website','url':'...'}]")),
                ('boost_count', models.PositiveIntegerField(default=0)),
                ('is_boosted', models.BooleanField(default=False)),
                ('boost_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channels',
                'ordering': ['-subscriber_count'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('media_url', models.CharField(blank=True, max_length=500, null=True)),
                ('media_type', models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='none', max_length=10)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_posts', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='channelapp.channel')),
            ],
            options={
                'db_table': 'channel_posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelBoostPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boost_days', models.PositiveIntegerField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_payments', to='channelapp.channel')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_boosts_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_boost_payments',
            },
        ),
        migrations.CreateModel(
            name='ChannelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='channelapp.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_views',
                'unique_together': {('channel', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChannelSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='channelapp.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_subscribers',
                'indexes': [models.Index(fields=['user'], name='channel_sub_user_id_192ff6_idx')],
                'unique_together': {('channel', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChannelPostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='channelapp.channelpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_post_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_post_reactions',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChannelPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='channelapp.channelpost')),
            ],
            options={
                'db_table': 'channel_post_comments',
                'indexes': [models.Index(fields=['post', 'created_at'], name='channel_pos_post_id_c8c81c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='channelpost',
            index=models.Index(fields=['channel', '-published_at'], name='channel_pos_channel_d81169_idx'),
        ),
        migrations.AddIndex(
            model_name='channelpost',
            index=models.Index(fields=['is_pinned'], name='channel_pos_is_pinn_129952_idx'),
        ),
        migrations.AddIndex(
            model_name='channelboostpayment',
            index=models.Index(fields=['channel'], name='channel_boo_channel_8af2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='channelboostpayment',
            index=models.Index(fields=['payment_status'], name='channel_boo_payment_66e54d_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['handle'], name='channels_handle_5f25e1_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['channel_type'], name='channels_channel_2bceca_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['category'], name='channels_categor_48c74c_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['is_boosted', 'boost_count'], name='channels_is_boos_8f48d6_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['category', 'subscriber_count'], name='channels_categor_fe9c3b_idx'),
        ),
    ]
